version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    networks:
      - cyborg
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9094,OUTSIDE://KAFKA_IP:9092
      KAFKA_LISTENERS: INSIDE://:9094,OUTSIDE://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    networks:
      - cyborg
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  clickhouse:
    image: 'yandex/clickhouse-server'
    restart: always
    container_name: clickhouse
    networks:
      - cyborg
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./clickhouse-persistence:/var/lib/clickhouse/
  grafana:
    image: 'grafana/grafana:latest'
    restart: always
    container_name: grafana
    env_file:
      - ./grafana/grafana.env
    ports:
      - '3000:3000'
    volumes: 
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana_data:/var/lib/grafana
    networks:
      - cyborg
  sysmon-beat:
    build:
      context: .
      dockerfile: Dockerfile-winlog
    container_name: sysmon-beat
    restart: always
    depends_on: 
      - kafka
    environment:
      CLICKHOUSE_HOST: clickhouse:9000
      KAFKA_BROKERS: kafka:9092
      KAFKA_GROUP: cyborg-winlog
      KAFKA_TOPICS: winlogbeat
      KAFKA_OLDEST: 'true'
      BUFFER_SIZE: 10000
      FlushInterval: 20
    networks:
      - cyborg

networks:
  cyborg:
    external: true
